### ISSUE TITLE
man2ronn:利用以前的文件

### ISSUE THREAD

**Issue by da-liii** [intetnet/manpages_zh#11]
刚写好一个漏洞百出的版本。不过已经可以用了。

**Comment by intetnet** [comment]
@sadhen 哈哈，不错哦。

你不用纠结在ronn上面，如果你有新的想法和工具，可以直接实施，manpages_zh没有要求使用什么特别的工具。

**Comment by da-liii** [comment]
主要感觉ronn挺不错的，另外我之前写过一整子markdown parser，对Markdown比较熟悉。所以觉得基于ronn做一些事情还挺容易的。

另外，我觉得基于列的想法挺好的。我觉得我们可以改一改ronn的源码。这样编辑的时候就不用考虑该多少字换行了。

**Comment by da-liii** [comment]
我现在的想法是维护一套ronn和man2ronn的工具。

翻译的时候，先用man2ronn从英文的manpages提取出ronn文件。再翻译好ronn文件，作为这个项目的源文件。

最后用ronn生成groff或者html。

不知道你是怎么翻译的？是直接打开一个man，参照着翻译吗？我觉得这样会带来很多格式上的问题。

**Comment by hosiet** [comment]
改源码是说处理时每发现_会_排到第80列即自动添加换行吗？好像挺不错的。

<del>可惜我没学过 ruby</del>

groff 本身有不少排版命令；有一些是 ronn markdown 实现不了的，例如指定缩进格数。我觉得翻译时可以不要局限于原格式。
虽然起步会比较困难，但如果能够维护一套转换工具的话会极大地简化翻译流程。

**Comment by intetnet** [comment]
@sadhen 我一般是用 `man -H` 生成网页文件，然后对照着一边翻译一边排版，`sadhen/man2ronn` 的想法挺好，我们可以翻出文档之后，直接修改英文的 ronn 文件和排版，当然也可以直接修改英文 ronn 文件。

@hosiet 对，从英文 manpages 到中文手册，需要预处理英文 manpages 文件、翻译、排版，然后可能不断地修改，这个过程的每一步都需要对应一个转换工具，比如预处理可以用 `man -H %` 生成网页或者通过 `man2ronn` 生成 ronn 文件，或许对这一步我们还需要更多的工具生成更多的格式。翻译我们可以使用 CAT 辅助翻译（比如 OmegaT )，通过创建一个群组的办法协作翻译，这样翻出来的东西会比较整齐，正规，这个里面的东西很多，先放下，我们以后讨论。排版需要用到翻译出来的文件，我觉得“早发布，常发布”是对的，哪怕只翻译了一句话，也应该及时转换成中文手册文件，也许恰好能帮助一些人，而且面对空白，人人都有畏惧心理，这时有点翻译总比什么都没有要更有助于吸收新的贡献，从这里就可以看到巨大的排版需要，如果能够减少重复排版的次数，就能大大提高产出率，这里就需要一个好用转换工具。

我想到一个流程，但不成熟，这几天弄出来开一个 issue，到时候我们可以讨论下。
