### ISSUE TITLE
@sadhen 添加为项目协作伙伴

### ISSUE THREAD

**Issue by intetnet** [intetnet/manpages_zh#14]
@sadhen 不好意思，一直忘了把你加到里面来，现在你可以自己合并推送了。

感谢

**Comment by da-liii** [comment]
谢谢。

我建立了一个man-pages-zh的组织，我们讨论一下，可以将现有的资源合理地整合进去。

比如工具和文档应该分开等等。比如我觉得coreutils的手册和procps的手册应该分为两个repo。这样就可以用branch来管理不同的版本软件包对应的不同版本的手册页。

现在这个repo有些乱。

**Comment by intetnet** [comment]
嗯，很久以前我就想建立一个大项目，里面可以放很多小项目，这样也能体现这个项目的公共属性。我注册的名字是 `manpages-zh`，但是还没有推送什么，因为感觉时机还不成熟，还有很多想法没有来得及实施，项目也存在很多不确定性。我这边暂时不能决定是否全盘采用  `man-pages-zh`，不过你可以先弄一下，如果可行的话，我会从你那里folk项目过来。

等想法稳定下来、翻译流程能够正常运转，我们再决定采用哪个。

感谢

**Comment by da-liii** [comment]
我觉得我们可以先在man-pages-zh这个组织的wiki repo里面讨论。总结出一些方案，困难等等，写到wiki repo的wiki上面。你觉得如何。

**Comment by da-liii** [comment]
@intetnet 抱歉，之前不知道已经有一个manpages-zh组织了。我觉得我们还是只用一个组织吧。就你那个组织好了

**Comment by intetnet** [comment]
@sadhen 我这边具体想法还没定下来，所以由你先行也不错。

对于我来说，最重要的不是怎么翻，而是有没有翻，我目前主要还是在 `intetnet/manpages_zh` 这边把基础性的东西弄好，既然有很多不确定性因素，我们一边翻译，一边研究吧。
