### ISSUE TITLE
@hoiset docbook的源文件在哪？

### ISSUE THREAD

**Issue by intetnet** [intetnet/manpages_zh#16]
你把docbook目录整理下，把可以复用的源文件放在根目录下的吧。

**Comment by hosiet** [comment]
那么我先对 docbook 目录下的文件解释一下：

之前我觉得 ronn 也许不太够用，想要寻求另外的写作方法，于是找到了 docbook 这一套写作方式；这里的文件是目前为止的成果。

docbook-xsl 是一套由 docbook XML 生成各类文档的转换文件，使用 XSLT，上游在 Sourceforge。它能够用来书写
man 手册页，所以我做了一点尝试，并且为了更好地符合需求自己做了修改，放在
docbook/xsl-stylesheets-1.78.1~manpages_zh 目录下。

目前写作的 docbook XML 文件放在 docbook/man1 目录下。

docbook 目录下的 dist.sh 是自动生成 man groff 文档与 HTML 文档的批处理脚本。

docbook 目录下的 docbook-man.css 是自己写的用于所生成的 html 文档的样式表。

已完成的成果已经放到项目根目录下的 man/ 目录与 html/ 目录下了。

我觉得那一套 XSL 文件可以专门开一个项目，不应与写作文件混放在这里。

另外，现在看来使用 XML 写作更适合于上游从头开始进行写作，可能不太适合于进行翻译；而且不少人对 XML 这一套不怎么感冒。如果能够对 ronn
工具进行改进，则这一套方法就不再存在优势了。总之我会再做一些工作，作为备选方法。

**Comment by intetnet** [comment]
好，我会对项目做些调整。

docbook 可能会满足一些人的需要，我会把它放到 https://github.com/manpages-zh 项目里面。如果你有什么想法，可以提出来。
