### ISSUE TITLE
你好，请问我的中文全显示为<?>是什么情况

### ISSUE THREAD

**Issue by shanbai** [intetnet/manpages_zh#18]
运行环境，andoid的termux终端，用vi打开文件中文显示正常

**Comment by hosiet** [comment]
termux 并不是一个完整的 linux 发行版，甚至没有 locale 支持。在 Android 上请考虑使用
https://play.google.com/store/apps/details?id=com.ssaurel.manpages 这样的软件，或者
GNURoot Debian 这样提供完整发行版环境的 App。

在 2016年7月22日週五 16:13，shanbai notifications@github.com 寫道：

**Comment by shanbai** [comment]
用了linuxonandroid的ubuntu14.04，装好中文环境，已可以使用，谢谢。

来自 魅蓝 note

-------- 原始邮件 --------
发件人：Boyuan Yang notifications@github.com
时间：周五 7月22日 16:22
收件人：manpages-zh/manpages_zh manpages_zh@noreply.github.com
抄送：shanbai wubohao@outlook.com,Author author@noreply.github.com
主题：Re: [manpages-zh/manpages_zh] 你好，请问我的中文全显示为<?>是什么情况 (#18)
