### ISSUE TITLE
中英文混排的建议

### ISSUE THREAD

**Issue by hosiet** [intetnet/manpages_zh#4]
基于<del>我的强迫症</del>美观原因，我觉得现在这样排版英文显示效果实在有些问题；考虑到 manpage 本身的局限性，我提一个折中方案：
-  对于中英文混排的大段落，使用英文句号+一个半角空格，中文句号之后加上一个半角空格；
-  对于中英文混排的大段落，在英文字符以及括号（使用英文括号）两边各加上一个空格；
-  对于短句以及没有中英混排问题的纯中文段落，使用正常全角逗号与全角句号；
-  在以上前提下，段落内在必要的地方换行。

不知您觉得怎么样？这样做能够在一定程度上缓解大量空格的出现，也使得中英混排显示较为正常，对于各类窗口大小都能一定程度的适应。

---

另，能否考虑同时接受使用 DocBook 生成 man 文档，以及裸写 groff 文档的内容呢？毕竟 ronn 已经五年没更新了，也需要考虑一下备用方案。

**Comment by intetnet** [comment]
嗯，目前是这样的：
1. 对于中英混排，我发现使用全角字符并不好看，所以现在统一使用了半角字符，在我这里可以显示的很漂亮了，对于全中文使用全角字符，一个手册出现两种格式，会不会出现排版杂乱的情况，当然最终以美观/简洁为上，我这几天研究一下，传上来几张图片，对比一下。
2. 英文字符和中文字符之间是需要加空格的，这个不仅是规范而且好看，只是在实际排版的时候，一行中出现空格会让groff认为这个行是由几个单词组成的，出现跳行的现象，这个是groff的问题，我发现groff并没有解决这个问题。
3. 换行是可以的，有些段确实太长了，看起来都觉得头大。

最后怎么生成man手册的事，其实都是可以的，这个由排版的人自己决定，因为最终我们要实现的是如下两个目的；
1. 能够生成手册页
2. 易于编写修改

实际上groff的语法很多，就像latex一样，而我们最终需要的很少，只需要几种格式而已，仅从我个人排版的角度来看，markdown很容易复用，ronn也可以满足我的需要。

我不太推荐裸写groff，因为不能满足第二条易于编写修改，不仅是对自己的，还是对其他想去修改手册的人。当然大多数人不需要考虑这个，也没必要为了手册页，专门学个排版，他们只需要翻译就好了，翻译好了提交上自然有人来排版，这个是排版人员的事。

你说的docbook我没试过，我最近在研究用po来生成手册，po是很好的格式，因为linux下的cat（计算机辅助翻译）能够很好的支持这个格式，最终来生成统一的语法规范和格式，你想，我们的翻译人员能够像专业翻译一样使用计算机来辅助翻译，交流记忆库，减少手工翻译的时间，想想就觉得很美好。

我会把你加到collaborator里面，你试试用docbook来生成手册吧，或许其他人觉得挺好，多条路应该能吸引更多的人加入吧。

**Comment by hosiet** [comment]
DocBook 的效果请参见我的 fork 的 docbook 分支；

另，写的 cd(1P) man page 部分采用了数字空格(U+2007)的 hack 方法，在局部进行了微调以避免换行问题。

**Comment by intetnet** [comment]
使用半角字符的md5sum：[图片待传]

使用全角字符的cd：[图片待传]

现在看在汉字中使用半角字符确实显得太紧凑了，应该多使用一些格式来避免汉字挤在一起。你的看起来不错，我这边也一点点改起来了，其他人也可以帮忙修改下。

对了，W3C的中文排版规范草稿已经出来了，不如大家都看看中文应该怎么排版吧。

http://www.w3.org/International/docs/chinese-layout/zh/
