### ISSUE TITLE
Github的glossary支持

### ISSUE THREAD

**Issue by da-liii** [intetnet/manpages_zh#6]
这样可能更加方便一些：
https://github.com/sadhen/texmacs_doc_zh/blob/master/glossary.csv

**Comment by intetnet** [comment]
csv格式我之前没用过，看你的展示起来像是对照翻译的东东。我想问:
- 这个具体是怎么实现的？怎么用它？
-  只有github能这样展示吗？用来做翻译能直接到导出吗？

**Comment by da-liii** [comment]
这个是Github的显示方案：
https://help.github.com/articles/rendering-csv-and-tsv-data/

主要是方便在线查

**Comment by intetnet** [comment]
哦，如果仅仅是演示的话可以参考这里，这是用ronn直接生成的网页，我用github pages做了一个网页。

ref：http://intetnet.github.io/html/list.html

我暂时感觉没有必要和精力去实现这个东西，或许你可以folk一下这个项目，用里面的文件自己实现一下。

你的文件可以直接request pull过来，没有理由不接受啊。

Best Regard
