### ISSUE TITLE
manpages_zh的文档问题

### ISSUE THREAD

**Issue by da-liii** [intetnet/manpages_zh#8]
这个项目的文档本身就比较混乱，我已经看了好一阵子，但还是没怎么搞明白怎么开始翻译。

我觉得先要把这个项目本身的文档写好。最基础的一点至少项目的markdown文件的全角和半角要统一。另外，注意到了一个markdown段落引出的多余的空格的问题。本人看着好揪心。

我能否在基本不改变原来内容的情况下，改一改文档的排版？

**Comment by da-liii** [comment]
另外，markdown文档(or ronn)本身的可读性也是蛮重要的。我觉得`##`后面应该要加一个空格。

**Comment by intetnet** [comment]
比较混乱是因为这个项目要面向三个群体:一个是使用者，另一个是翻译人员，还有就是排版人员了。面向使用者是因为必须要告诉他们如何使用man手册，怎么配置。面向翻译人员是因为这样能聚集更多的人，有些人可能不熟悉各种排版的软件的使用，但翻译还是力所能及的，所以要告诉他们如何加入进来，面向排版人员是因为最终从翻译到手册还有一个过程，需要很多拥有相关知识的人才能胜任，所以就要传播这些知识了。

其实我一直在想办法，我想过面向不同的群体使用不同的分支，但觉得不够好，因为太分散，反而不直观，或许你们可以想到更好的办法。

一个issue一个问题吧。

**Comment by intetnet** [comment]
项目的文档我一直在改呢。

我一开始写项目文档的时候用的是fcitx输入法，默认汉语是全角的，后来修改的时候用vimim，因为我个人觉得手册文件用全角不好看，就在vimim里设置成了使用半角，所以修改的时候有些地方一不小心就混用了全角半角，真是不好意思啊。

汉语还是用汉语的全角吧，半角太挤了，只适合空格分割的英语，不仅是项目文档还有手册文件都统一这样做吧。我考虑在这个项目使用w3c的中文排版规范，如果你们都没有异议的话，就以该规范为准。

你可以直接修改项目文件的，也非常欢迎你这么做。

**Comment by intetnet** [comment]
如果##后加空格不影响排版的话，是可以加空格的。

我以前没想到过这个，一个脚本就可以解决这个问题了，有时间我会去做。

感谢。
