### ISSUE TITLE
全角半角的建议

### ISSUE THREAD

**Issue by da-liii** [intetnet/manpages_zh#9]
我觉得该用全角的地方应该都用全角。因为用全角的话，写脚本全部改为半角很方便。而用半角，要是有一天排版技术改善了，全角比较好看的话，一般是没法自动化转化为全角的吧！！

排版不支持的地方，我觉得我们不应该改文档来适应落后的排版工具。而是应该想办法改变排版的工具。这是我翻译TeXmacs文档的体验。

**Comment by intetnet** [comment]
全角半角的问题在issue8里已经回答了，关于转换的问题，这个是很简单的，比如vim里一个命令就可以解决半角转全角的问题，如下:

```
    %s/./。/g
```

**Comment by intetnet** [comment]
这里是manpages_zh，我们还能用什么工具呢？

注:如果有更好的工具的话，是可以考虑的。

**Comment by da-liii** [comment]
半角转全角全局替换我自然是知道的。不过我要强调的是，半角转全角无可避免地会带来很多人工的检查。因为用到.的地方实在太多了。
